# Generated by Django 4.2.7 on 2025-09-09 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar ($)'), ('EUR', 'Euro (€)'), ('GBP', 'British Pound (£)'), ('JPY', 'Japanese Yen (¥)'), ('CAD', 'Canadian Dollar (C$)'), ('AUD', 'Australian Dollar (A$)'), ('CHF', 'Swiss Franc (CHF)'), ('CNY', 'Chinese Yuan (¥)'), ('INR', 'Indian Rupee (₹)'), ('BRL', 'Brazilian Real (R$)'), ('MXN', 'Mexican Peso ($)'), ('KRW', 'South Korean Won (₩)'), ('SGD', 'Singapore Dollar (S$)'), ('HKD', 'Hong Kong Dollar (HK$)'), ('NZD', 'New Zealand Dollar (NZ$)'), ('SEK', 'Swedish Krona (kr)'), ('NOK', 'Norwegian Krone (kr)'), ('DKK', 'Danish Krone (kr)'), ('PLN', 'Polish Zloty (zł)'), ('CZK', 'Czech Koruna (Kč)'), ('HUF', 'Hungarian Forint (Ft)'), ('RUB', 'Russian Ruble (₽)'), ('TRY', 'Turkish Lira (₺)'), ('ZAR', 'South African Rand (R)'), ('AED', 'UAE Dirham (د.إ)'), ('SAR', 'Saudi Riyal (﷼)'), ('QAR', 'Qatari Riyal (﷼)'), ('KWD', 'Kuwaiti Dinar (د.ك)'), ('BHD', 'Bahraini Dinar (د.ب)'), ('OMR', 'Omani Rial (﷼)'), ('JOD', 'Jordanian Dinar (د.ا)'), ('LBP', 'Lebanese Pound (ل.ل)'), ('EGP', 'Egyptian Pound (ج.م)'), ('ILS', 'Israeli Shekel (₪)'), ('THB', 'Thai Baht (฿)'), ('MYR', 'Malaysian Ringgit (RM)'), ('IDR', 'Indonesian Rupiah (Rp)'), ('PHP', 'Philippine Peso (₱)'), ('VND', 'Vietnamese Dong (₫)'), ('TWD', 'Taiwan Dollar (NT$)'), ('PKR', 'Pakistani Rupee (₨)'), ('BDT', 'Bangladeshi Taka (৳)'), ('LKR', 'Sri Lankan Rupee (₨)'), ('NPR', 'Nepalese Rupee (₨)'), ('MMK', 'Myanmar Kyat (K)'), ('KHR', 'Cambodian Riel (៛)'), ('LAK', 'Lao Kip (₭)'), ('BND', 'Brunei Dollar (B$)'), ('FJD', 'Fijian Dollar (FJ$)'), ('PGK', 'Papua New Guinea Kina (K)'), ('SBD', 'Solomon Islands Dollar (SI$)'), ('VUV', 'Vanuatu Vatu (Vt)'), ('WST', 'Samoan Tala (WS$)'), ('TOP', 'Tongan Paʻanga (T$)'), ('XPF', 'CFP Franc (₣)')], default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='recurringexpense',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar ($)'), ('EUR', 'Euro (€)'), ('GBP', 'British Pound (£)'), ('JPY', 'Japanese Yen (¥)'), ('CAD', 'Canadian Dollar (C$)'), ('AUD', 'Australian Dollar (A$)'), ('CHF', 'Swiss Franc (CHF)'), ('CNY', 'Chinese Yuan (¥)'), ('INR', 'Indian Rupee (₹)'), ('BRL', 'Brazilian Real (R$)'), ('MXN', 'Mexican Peso ($)'), ('KRW', 'South Korean Won (₩)'), ('SGD', 'Singapore Dollar (S$)'), ('HKD', 'Hong Kong Dollar (HK$)'), ('NZD', 'New Zealand Dollar (NZ$)'), ('SEK', 'Swedish Krona (kr)'), ('NOK', 'Norwegian Krone (kr)'), ('DKK', 'Danish Krone (kr)'), ('PLN', 'Polish Zloty (zł)'), ('CZK', 'Czech Koruna (Kč)'), ('HUF', 'Hungarian Forint (Ft)'), ('RUB', 'Russian Ruble (₽)'), ('TRY', 'Turkish Lira (₺)'), ('ZAR', 'South African Rand (R)'), ('AED', 'UAE Dirham (د.إ)'), ('SAR', 'Saudi Riyal (﷼)'), ('QAR', 'Qatari Riyal (﷼)'), ('KWD', 'Kuwaiti Dinar (د.ك)'), ('BHD', 'Bahraini Dinar (د.ب)'), ('OMR', 'Omani Rial (﷼)'), ('JOD', 'Jordanian Dinar (د.ا)'), ('LBP', 'Lebanese Pound (ل.ل)'), ('EGP', 'Egyptian Pound (ج.م)'), ('ILS', 'Israeli Shekel (₪)'), ('THB', 'Thai Baht (฿)'), ('MYR', 'Malaysian Ringgit (RM)'), ('IDR', 'Indonesian Rupiah (Rp)'), ('PHP', 'Philippine Peso (₱)'), ('VND', 'Vietnamese Dong (₫)'), ('TWD', 'Taiwan Dollar (NT$)'), ('PKR', 'Pakistani Rupee (₨)'), ('BDT', 'Bangladeshi Taka (৳)'), ('LKR', 'Sri Lankan Rupee (₨)'), ('NPR', 'Nepalese Rupee (₨)'), ('MMK', 'Myanmar Kyat (K)'), ('KHR', 'Cambodian Riel (៛)'), ('LAK', 'Lao Kip (₭)'), ('BND', 'Brunei Dollar (B$)'), ('FJD', 'Fijian Dollar (FJ$)'), ('PGK', 'Papua New Guinea Kina (K)'), ('SBD', 'Solomon Islands Dollar (SI$)'), ('VUV', 'Vanuatu Vatu (Vt)'), ('WST', 'Samoan Tala (WS$)'), ('TOP', 'Tongan Paʻanga (T$)'), ('XPF', 'CFP Franc (₣)')], default='USD', max_length=3),
        ),
    ]
