# Generated by Django 4.2.7 on 2025-09-09 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expense_currency_recurringexpense_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='recurringexpense',
            name='currency',
        ),
    ]
